### ISSUE TITLE
Live view throwing 'error 97' after a few seconds of working (50D)

### ISSUE THREAD

**Issue by enigmashot** [kritzikratzi/edsdk-processing#2]
Hi Hansi!

Thank you so much for your library. It's incredible how easy it is to use.

I have been trying to use it with my canon 50D camera. The library used to work fine, but now the live view goes blank after a few seconds of working and I get a repeating error message :

"Could not check live view status: An error occurred while getting kEdsPropID_Evf_Mode data (error 97: EDS_ERR_INVALID_HANDLE - Function Handle Error)"

I commented out all the setting/quality changes, etc to see if any of those are affecting it but no luck. I am getting the same erratic behavior with the basic "Hello.pde" that you provided.

Did anyone else encounter something like this? what could be causing the problem?

Thanks!

**Comment by kritzikratzi** [comment]
hey! 

i wish i had an idea, but i really don't :/ 
does live view work on your camera when it's not connected to the pc?

**Comment by enigmashot** [comment]
Yes, Live view works fine on its own. I will try the code on a 5D Mkll and see if I get the same problem.

**Comment by enigmashot** [comment]
Okay, I guess it wasn't an issue after all. Apparently, you can get "Error 97" when your camera goes to standby mode after a period of inactivity. 

Although, when I posted the issue, I was getting the error just 5 seconds after live view started and when the camera was still active. But a simple windows reboot and cache clearing solved that. After that, I was getting error 97 consistently at about the 5 minute mark instead, and sure enough, the camera was set to go to standby after 5 min.s. I just set the "Auto Power Off" setting to OFF and no more problems.

Thanks for responding so quickly!

**Comment by kritzikratzi** [comment]
kk, glad you figured it out :)
